-- ============================================================
-- AeroTwin / SIH Full Supabase Database Schema
-- Run this complete script in the Supabase SQL Editor
-- ============================================================

-- 1. PROFILES TABLE (User profiles & Role-Based Access)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  email TEXT,
  role TEXT DEFAULT 'viewer' CHECK (role IN ('viewer', 'unset', 'gcs_operator', 'propulsion_engineer', 'maintenance_tech')),
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS on profiles
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Profiles Policies
DROP POLICY IF EXISTS "Users can view their own profile" ON public.profiles;
CREATE POLICY "Users can view their own profile"
  ON public.profiles FOR SELECT
  USING (auth.uid() = id);

DROP POLICY IF EXISTS "Users can update their own profile" ON public.profiles;
CREATE POLICY "Users can update their own profile"
  ON public.profiles FOR UPDATE
  USING (auth.uid() = id);

DROP POLICY IF EXISTS "Users can insert their own profile" ON public.profiles;
CREATE POLICY "Users can insert their own profile"
  ON public.profiles FOR INSERT
  WITH CHECK (auth.uid() = id);


-- 2. AUTOMATIC PROFILE CREATION TRIGGER (ON USER SIGNUP)
-- ------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  INSERT INTO public.profiles (id, email, role)
  VALUES (
    NEW.id,
    NEW.email,
    COALESCE(NEW.raw_user_meta_data->>'role', 'viewer')
  )
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$$;

-- Drop trigger if exists and recreate
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_new_user();


-- 3. SECURE ROLE SELECTION RPC FUNCTION
-- ------------------------------------------------------------
-- Allows first-time users to set their operational role exactly once
CREATE OR REPLACE FUNCTION public.set_initial_role(new_role TEXT)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  -- Validate input role
  IF new_role NOT IN ('gcs_operator', 'propulsion_engineer', 'maintenance_tech') THEN
    RAISE EXCEPTION 'Invalid role specified: %', new_role;
  END IF;

  -- Update profile if role is 'viewer', 'unset', or NULL
  UPDATE public.profiles
  SET role = new_role,
      updated_at = timezone('utc'::text, now())
  WHERE id = auth.uid()
    AND (role = 'viewer' OR role = 'unset' OR role IS NULL);

  IF NOT FOUND THEN
    -- Either user is already assigned a role or row doesn't exist yet
    INSERT INTO public.profiles (id, email, role, updated_at)
    VALUES (auth.uid(), auth.jwt()->>'email', new_role, timezone('utc'::text, now()))
    ON CONFLICT (id) DO UPDATE
      SET role = new_role,
          updated_at = timezone('utc'::text, now())
      WHERE public.profiles.role = 'viewer' OR public.profiles.role = 'unset' OR public.profiles.role IS NULL;
  END IF;
END;
$$;

-- Grant execution permissions
GRANT EXECUTE ON FUNCTION public.set_initial_role(TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.set_initial_role(TEXT) TO anon;


-- 4. TELEMETRY ANOMALIES TABLE (Backend Anomaly Logging)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.telemetry_anomalies (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  timestamp TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
  anomaly_score DOUBLE PRECISION,
  is_anomaly BOOLEAN,
  rul_predicted DOUBLE PRECISION,
  severity TEXT,
  metrics JSONB
);

-- Enable RLS
ALTER TABLE public.telemetry_anomalies ENABLE ROW LEVEL SECURITY;

-- Allow reading anomalies for authenticated users
DROP POLICY IF EXISTS "Authenticated users can read anomalies" ON public.telemetry_anomalies;
CREATE POLICY "Authenticated users can read anomalies"
  ON public.telemetry_anomalies FOR SELECT
  TO authenticated
  USING (true);

-- Allow service role / backend to insert anomalies
DROP POLICY IF EXISTS "Service can insert anomalies" ON public.telemetry_anomalies;
CREATE POLICY "Service can insert anomalies"
  ON public.telemetry_anomalies FOR INSERT
  WITH CHECK (true);


-- 5. NASA CMAPSS TELEMETRY TABLE (Optional Dataset Storage)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.nasa_cmapss_telemetry (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dataset_id TEXT,
  unit INT,
  cycle INT,
  setting1 DOUBLE PRECISION,
  setting2 DOUBLE PRECISION,
  setting3 DOUBLE PRECISION,
  sensor_1 DOUBLE PRECISION,
  sensor_2 DOUBLE PRECISION,
  sensor_3 DOUBLE PRECISION,
  sensor_4 DOUBLE PRECISION,
  sensor_5 DOUBLE PRECISION,
  sensor_6 DOUBLE PRECISION,
  sensor_7 DOUBLE PRECISION,
  sensor_8 DOUBLE PRECISION,
  sensor_9 DOUBLE PRECISION,
  sensor_10 DOUBLE PRECISION,
  sensor_11 DOUBLE PRECISION,
  sensor_12 DOUBLE PRECISION,
  sensor_13 DOUBLE PRECISION,
  sensor_14 DOUBLE PRECISION,
  sensor_15 DOUBLE PRECISION,
  sensor_16 DOUBLE PRECISION,
  sensor_17 DOUBLE PRECISION,
  sensor_18 DOUBLE PRECISION,
  sensor_19 DOUBLE PRECISION,
  sensor_20 DOUBLE PRECISION,
  sensor_21 DOUBLE PRECISION,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.nasa_cmapss_telemetry ENABLE ROW LEVEL SECURITY;

-- Allow reading NASA data
DROP POLICY IF EXISTS "Allow select for all" ON public.nasa_cmapss_telemetry;
CREATE POLICY "Allow select for all"
  ON public.nasa_cmapss_telemetry FOR SELECT
  USING (true);

DROP POLICY IF EXISTS "Allow insert for service" ON public.nasa_cmapss_telemetry;
CREATE POLICY "Allow insert for service"
  ON public.nasa_cmapss_telemetry FOR INSERT
  WITH CHECK (true);
